feat: Added support for django3.2
edx/api-doc-tools pull request #89
Opened 2021-07-19 15:46 UTC by Jawayria

JIRA: https://openedx.atlassian.net/browse/BOM-2690

2021-07-20 20:08 UTC, nedbat commented on CHANGELOG.rst
> +* Added support for django 3.0, 3.1 and 3.2
We don't need Django 3.0 or 3.1, right? Can't we simplify by just keeping Django 3.2?

2021-07-20 20:10 UTC, nedbat requested changes
We aren't going to use this with Django 3.0 or 3.1, so we can simplify, unless I am missing something?

2021-07-26 11:21 UTC, Jawayria commented
> We aren't going to use this with Django 3.0 or 3.1, so we can simplify, unless I am missing something?
we need to add support for Django 3.0 and 3.1 and remove any deprecation warnings raised by them as these warnings may cause failures with Django3.2. We should make sure that the fixes we make work with Django 3.0, 3.1 and 3.2

2021-08-10 10:34 UTC, mraarif commented on .travis.yml
> +        - DEPLOY_PYPI=true
we don't need this variable since there's a separate Github workflow handling PyPi deployments

2021-08-12 09:43 UTC, awais786 approved these changes

2021-09-01 18:37 UTC, nedbat approved these changes

2021-09-03 13:02 UTC, merged